dist: trusty
sudo: false
language: generic
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- shellcheck tzzzz
- restructuredtext-lint --encoding=UTF-8 README
- mkdir -m 700 -p ~/.config/tzzzz
- echo America/New_York Europe/Warsaw Australia/Perth > ~/.config/tzzzz/config 
- ./tzzzz 

# vim:ts=2 sts=2 sw=2 et
